### ISSUE TITLE
OJS 3.3.0-10: All administrative links are broken

### ISSUE THREAD

**Issue by Helyfoxer** [asmecher/pkp-lib#16]
After upgrading to 3.3.0-10 we having bug with broken link to administrative page.
_UPDATE: on clean setup 3.3.0-10 situation is the same._

In user profile drop-down menu the system generates a link like `https://SITE_NAME/:///SITE_NAME/admin/index` , but admin page opens by `https://SITE_NAME/index/admin` ( _restful_urls = On_ ) and opening page got errors in contained links and form's urls.

I've checked that `lib/pkp/classes/services/PKPNavigationMenuService.inc.php` in this version already looks like https://github.com/asmecher/pkp-lib/commit/e9f5360ffe6638ff77e7c76db9496094eaf7759a

Only https://github.com/asmecher/pkp-lib/commit/bdbfc6ba5da486d3c3949782637a6513ab8d6367 patch was applied to change `lib/pkp` dir content.

Temporalily I added to `lib/pkp/classes/services/PKPNavigationMenuService.inc.php`
```
$navigationMenuItem->setUrl('/index/admin');
```
after
```
case NMI_TYPE_ADMINISTRATION:
	$navigationMenuItem->setUrl($dispatcher->url(
	$request,
	ROUTE_PAGE,
	'index',
	'admin',
	'index',
	null
	));
```
while I trying to analyse reasons.

And it did not help to fix the link to the admin page in the last link of the Dasboard left menu - there link is shaped by different way.

But as I wrote above, the administration page is useless.

Because all links and urls on it are also with errors.

**Comment by asmecher** [comment]
@Helyfoxer, could you open this issue on https://github.com/pkp/pkp-lib instead of https://github.com/asmecher/pkp-lib?

**Comment by Helyfoxer** [comment]
Ok. Thanks for the guidance!
